# Navigate with hjkl through panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
#
# Resize panes with Ctrl + b + arrow keys
bind -r Left  resize-pane -L 5
bind -r Down  resize-pane -D 5
bind -r Up    resize-pane -U 5
bind -r Right resize-pane -R 5

set -g mouse on

setw -g mode-keys vi
