code --install-extension charliermarsh.ruff
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension hediet.vscode-drawio
code --install-extension jdinhlife.gruvbox
code --install-extension mechatroner.rainbow-csv
code --install-extension mermaidchart.vscode-mermaid-chart
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension myriad-dreamin.tinymist
code --install-extension njpwerner.autodocstring
code --install-extension nvarner.typst-lsp
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tomoki1207.pdf
code --install-extension vscodevim.vim
